title: Meir Elbaz

about_me: >-
  יש לי ניסיון רב בפיתוח Full Stack, גם מעבר לצד התכנותי של המערכת, בין בשלב ההקמה של התשתית ועד לעיצוב הממשק, בעבר כמפתח PHP וכיום כמפתח Python.
  הרחבתי את תחום הידע שלי גם לתכנות מתקדם בשפות C/C++, השכלה אקדמאית הכרחית ונושאים כלליים בפיתוח תוכנה.

skills:
  - Python
  - Docker
  - React
  - Django
  - HTML
  - CSS
  - Bootstrap

year_of_birth: 1991

phone: 0539630263

mail: maornet@gmail.com

github: https://github.com/meirdev/

languages:
  - name: עברית
    level: שפת אם
  - name: אנגלית
    level: רמה גבוהה

work_experience:
  - title: מפתח Python
    institution_name: מובילאיי
    location: ירושלים
    years: 2019-2022
    intro: >-
      עבודה במחלקת הרכב האוטונומי, בנייה ותכנון של מערכות לתפעול הצי: ניטור הרכבים, עדכון גרסאות, ניהול תקלות , שליחת התראות, תחזוקה והרצה של גרסאות
    more_info:
      - "פיתוח Backend ב: Django & DRF"
      - "פיתוח Frontend ב: React & Bootstrap"
      - "עבודה מול תשתיות בענן: AWS Lambda & DynamoDB"
      - "תכנון ויצירה של אוטומציות: Jenkins"
      - הרמת סביבות עבודה עבור פיתוח ופרודקשן בעזרת Docker

education:
  computers:
    - title: תכנית KickStart להכשרת מפתחי תוכנה
      institution_name: Experis Software R&D Ltd
      location: תל אביב
      years: 2018
      intro: >-
        תכנית Experis KickStart נמשכת כשישה חודשים ומיועדת להכשרת אקדמאים מצטיינים למקצועות התוכנה. התכנית בנויה על בסיס צורכי התעשיה ומשלבת תיאוריה ופרקטיקה המועברים על ידי מנטורים בכירים עתירי ניסיון בתעשייה. הסדנא מבוססת על תיאוריה ועבודה לפי סטנדרטים תעשייתיים המדגישים: maintainability, modularity & optimization.
      more_info:
        - "Low level: עבודה עם זיכרון, תכנון מתאים לניצול היררכיית זיכרון (cache)"
        - Multithreading, Multi Cores, Synchronization במיוחד לצרכי Realtime / Embedded
        - "תכנות מתקדם בשפת C: שימוש בפוינטרים מבני נתונים, רקורסיה"
        - "תכנות מערכת: עבודה עם מערכת ההפעלה, תקשורת בין תהליכים"
        - "Multithreading: סינכרון בין תהליכים, תכנון מערכת מרובת  משימות"
        - Object Oriented Design
        - Networking, TCP/IP
        - Data Structures and Algorithms
        - Advanced C++, STL, Generic Programming

    - title: WeCode
      institution_name: המרכז הבינתחומי
      location: הרצליה
      years: 2018
      intro: בוטקאמפ אקדמי-מקצועי להכשרת מפתחי תוכנה
      more_info:
        - מבוא למדעי המחשב (ב-Python)
        - מבני נתונים
        - תכנות מתקדם

    - title: קורסים במדעי המחשב
      institution_name: האוניברסיטה הפתוחה
      location: מקוון
      years: 2016
      more_info:
        - מבוא למדעי המחשב ב-JAVA
        - מעבדה בתכנות מערכות בשפת C
        - מערכות ספרתיות

    - title: קורס QA
      institution_name: המכללה למנהל
      location: פתח תקווה
      years: 2015-2016
      more_info:
        - סיום בהצטיינות
        - תעודת הסמכה של ISTQB

  general:
    - title: לימודי קודש
      institution_name: ישיבת דבר-שמואל
      location: פתח תקווה
      years: 2011-2017

    - title: מגמת אלקטרוניקה
      institution_name: תיכון דנצינגר
      location: קריית שמונה
      years: 2007-2010
      more_info:
        - 12 שנות לימוד
